### ISSUE TITLE
並べ方

### ISSUE THREAD

**Issue by c0b21043** [C0B21013/ProjExD#10]
https://github.com/C0B21013/ProjExD/blob/4b1537b3f41ecb71c58f2119d4ca0fbea2f06305/ex04/dodge_bomb.py#L45
横に並べるのも良いですが、それだと横に長くなってしまうのでそれぞれひとつずつ定義してもいいのかなと思いました。

**Comment by C0B21013** [comment]
ありがとうございます。修正しました。
