### ISSUE TITLE
こうかとん即死・即クリアバグの可能性

### ISSUE THREAD

**Issue by a123ktx** [C0B21013/ProjExD#11]
https://github.com/C0B21013/ProjExD/blob/1f2b110710a43c8eaeae10949604ff2f04df3c95/ex04/dodge_bomb.py#L54
こうかとんと重なる位置にオブジェクトが発生すると、スタートしてすぐに回収してしまうケースがあります
範囲指定を調整するといいかもしれません

**Comment by C0B21013** [comment]
ありがとうございます。修正しました。
