### ISSUE TITLE
ゲームオーバーの追加

### ISSUE THREAD

**Issue by a123ktx** [C0B21013/ProjExD#12]
私は
class Game_over():
    #Game_overを表示するクラス

    def __init__(self):
        self.font = pg.font.Font(None, 110)
        self.text = self.font.render("GAME_OVER", True, (255, 0, 0))
    

    def blit(self, scr):
        scr.sfc.blit(self.text, [scr.rct.centerx/2, scr.rct.centery/2]) 

でゲームオーバーの描写をしました
ゲーム終了前にブリットすれば表示されます

**Comment by C0B21013** [comment]
ありがとうございます。修正しました。
